name: employee_attendance
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.10.25
  flutter_dotenv: ^5.1.0
  provider: ^6.1.1
  font_awesome_flutter: ^10.6.0
  slide_to_act: ^2.0.2
  intl: ^0.19.0
  simple_month_year_picker: ^1.0.5
  geolocator: ^10.1.0
  permission_handler: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
